apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-web-single-host-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-web-single-host
  template:
    metadata:
      labels:
        app: base-web-single-host
        maxModuleCount: "10"
    spec:
      containers:
        - name: app
          image: serverless-registry.cn-shanghai.cr.aliyuncs.com/opensource/base-log4j2:0.1.2
          ports:
            - containerPort: 8080
            - containerPort: 1238
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
---
## create service
apiVersion: v1
kind: Service
metadata:
  name: base-web-single-host-service
spec:
    selector:
        app: base-web-single-host
    type: NodePort
    ports:
        - name: http-port
          protocol: TCP
          port: 8080
          targetPort: 8080
          nodePort: 30080
#---
#    - 通过kubectl apply -f base-deployment.yaml创建应用
#    - 通过kubectl get pods -o wide查看pod的ip地址
#    - 通过kubectl get svc查看service的nodePort
#    - 通过curl http://nodeip:nodePort访问应用
#    - 通过kubectl delete -f base-deployment.yaml删除应用
#    - 通过kubectl delete svc base-web-single-host-service删除service
#    - 通过kubectl delete deployment base-web-single-host-deployment删除deployment