apiVersion: v1
kind: Service
metadata:
  name: dynamic-stock-service
spec:
  selector:
    app: dynamic-stock
  type: NodePort
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080