apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-stock-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-stock
  template:
    metadata:
      labels:
        app: dynamic-stock
        maxModuleCount: "10"
    spec:
      containers:
        - name: app
          image: serverless-registry.cn-shanghai.cr.aliyuncs.com/opensource/test/dynamic-stock-mng:0.0.1-samples
          ports:
            - containerPort: 8080
            - containerPort: 1238
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"