apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-controller
  labels:
    app: module-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: module-controller
  template:
    metadata:
      labels:
        app: module-controller
    spec:
      serviceAccountName: controller-manager
      containers:
        - name: module-controller
          image: serverless-registry.cn-shanghai.cr.aliyuncs.com/opensource/test/module-controller:v0.6.3
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
