---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serverless.alipay.com
  resources:
  - moduledeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serverless.alipay.com
  resources:
  - moduledeployments/finalizers
  verbs:
  - update
- apiGroups:
  - serverless.alipay.com
  resources:
  - moduledeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - serverless.alipay.com
  resources:
  - modulereplicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serverless.alipay.com
  resources:
  - modulereplicasets/finalizers
  verbs:
  - update
- apiGroups:
  - serverless.alipay.com
  resources:
  - modulereplicasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - serverless.alipay.com
  resources:
  - modules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serverless.alipay.com
  resources:
  - modules/finalizers
  verbs:
  - update
- apiGroups:
  - serverless.alipay.com
  resources:
  - modules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - serverless.alipay.com
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serverless.alipay.com
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - serverless.alipay.com
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
